version: '3'

services:
  server:
    container_name: SERVER_ESHOP
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: MONGODB_DB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  redis-server:
    image: 'redis'
    container_name: REDIS_DB
    ports:
      - '6379:6379'